const API_MI_ESTADIA=window.apiUrl("/api/seguimiento-estadia/mi-seguimiento");
document.addEventListener("DOMContentLoaded",cargarMiEstadia);
async function cargarMiEstadia(){
    try{const r=await fetch(API_MI_ESTADIA);const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.mensaje||"No fue posible consultar tu seguimiento.");render(d.seguimiento||{},d.documentos||{})}catch(e){console.error(e);document.getElementById("estadoDocumental").className="status-banner warn";document.getElementById("estadoDocumental").textContent=e.message}
}
function render(s,docs){
    const completos=docs.completos===true,estado=document.getElementById("estadoDocumental");estado.className=`status-banner ${completos?"ok":"warn"}`;estado.textContent=completos?"Tu documentación está completa. La administración ya puede contestar tus formularios individuales.":"Tus formularios todavía están bloqueados hasta completar y liberar las tres cartas requeridas.";
    document.getElementById("documentosGrid").innerHTML=`<div class="metric"><small>Carta de presentación</small><strong>${docs.cartaPresentacion?"Aceptada ✓":"Pendiente"}</strong></div><div class="metric"><small>Carta de aceptación</small><strong>${docs.cartaAceptacion?"Liberada ✓":"Pendiente"}</strong></div><div class="metric"><small>Carta de término</small><strong>${docs.cartaTermino?"Liberada ✓":"Pendiente"}</strong></div>`;
    const asesor=document.getElementById("asesorBox");if(s.asesorNombre){asesor.innerHTML=`<div class="advisor-icon">👤</div><div><strong>${escapeHtml(s.asesorNombre)}</strong><small>${escapeHtml(s.asesorCorreo||"Asesor Empresarial")}</small></div>`}else{asesor.innerHTML='<div class="advisor-icon">👤</div><div><strong>Pendiente de asignación</strong><small>La administración todavía no ha asignado un asesor empresarial.</small></div>'}
    pintar("Empresa",s.empresa===true,s.fechaEmpresa,completos);pintar("Satisfaccion",s.satisfaccion===true,s.fechaSatisfaccion,completos);
}
function pintar(nombre,hecho,fecha,completos){const badge=document.getElementById("badge"+nombre),texto=document.getElementById("texto"+nombre);if(hecho){badge.className="badge done";badge.textContent="Contestado ✓";texto.textContent=`La administración ya contestó este formulario${fecha?" el "+new Date(fecha).toLocaleDateString("es-MX"):""}.`;return}if(!completos){badge.className="badge locked";badge.textContent="Bloqueado";texto.textContent="Pendiente de completar la documentación requerida.";return}badge.className="badge pending";badge.textContent="Pendiente";texto.textContent="La documentación ya está completa. El formulario está pendiente de ser contestado por la administración."}
function escapeHtml(v){return String(v??"").replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
