const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const periodos=fs.readFileSync(path.join(__dirname,'../js/periodos.js'),'utf8'),ardia=fs.readFileSync(path.join(__dirname,'../js/ardia-global.js'),'utf8');
function clasificar(d){const window={};vm.runInNewContext(periodos,{window,Date});return {...window.PMOPeriodos.clasificar(d)};}
test('periodo capturado tiene prioridad sobre la fecha y su año se conserva',()=>assert.deepEqual(clasificar({periodoEstadia:'Mayo - Agosto 2027',fechaInicio:'2026-01-01'}),{clave:'mayo-agosto',nombre:'Mayo–Agosto',anio:'2027'}));
test('las fechas de inicio en límites cuatrimestrales no cambian por zona horaria',()=>{for(const [fecha,grupo]of [['2026-01-01','enero-abril'],['2026-04-30','enero-abril'],['2026-05-01','mayo-agosto'],['2026-08-31','mayo-agosto'],['2026-09-01','septiembre-diciembre'],['2026-12-31','septiembre-diciembre']])assert.equal(clasificar({fechaInicio:fecha}).clave,grupo);});
test('datos ausentes o fechas inexistentes conservan Sin periodo',()=>{assert.equal(clasificar({fechaRegistro:'2026-09-01'}).clave,'');assert.equal(clasificar({fechaInicio:'2026-02-30'}).clave,'');assert.equal(clasificar({fechaInicio:'2026-13-01'}).clave,'');});
test('un periodo que cruza años usa su primer mes y año de inicio',()=>assert.deepEqual(clasificar({periodo:'Septiembre 2026 - Enero 2027'}),{clave:'septiembre-diciembre',nombre:'Septiembre–Diciembre',anio:'2026'}));
test('acepta año bisiesto real y distingue cohortes',()=>{assert.equal(clasificar({fechaInicio:'2024-02-29'}).anio,'2024');assert.equal(clasificar({fechaInicio:'2025-02-29'}).clave,'');});
async function bot(pagina,token,restaurar){let tocado=0;const window={location:{pathname:'/'+pagina},restaurarSesionPMO:restaurar};const document={readyState:'complete',createElement(){tocado++;throw new Error('No debe montar sin sesión confirmada');}};
vm.runInNewContext(ardia,{window,document,localStorage:{getItem:()=>token}});await Promise.resolve();await Promise.resolve();return tocado;}
test('Ard.IA no aparece en login o registro ni consulta sesiones en páginas públicas',async()=>{for(const pagina of ['login.html','register.html'])assert.equal(await bot(pagina,'antiguo',()=>{throw new Error('No consultar');}),0);});
test('Ard.IA no aparece por una identidad local sin token ni con servidor sin confirmar sesión',async()=>{assert.equal(await bot('dashboard.html','',()=>{throw new Error('No consultar');}),0);assert.equal(await bot('dashboard.html','token',async()=>null),0);});
test('una validación retrasada de otra sesión no monta el asistente',async()=>{let t='anterior',terminar,tocado=0;const window={location:{pathname:'/dashboard.html'},restaurarSesionPMO:()=>new Promise(r=>terminar=r)};
vm.runInNewContext(ardia,{window,document:{readyState:'complete',createElement(){tocado++;}},localStorage:{getItem:()=>t}});t='nueva';terminar({id:7});await Promise.resolve();assert.equal(tocado,0);});
